version: '3.5'

# 6100 - auth
# 6101 - db_auth
# 6200 - data
# 6201 - db_data

services:
  db_auth:
    container_name: db_auth
    ports:
      - "6101:6101"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.3-alpine3.17
    command: 
      - "postgres"
      - "-c"
      - "port:6101"
    volumes:
      - db_auth_vol:/var/lib/postgresql/data/
volumes:
  db_auth_vol: {}
